export const CUSTOMER_PAGE_LIMIT = 10
export const CUSTOMER_HISTORY_PAGE_LIMIT = 20
export const CUSTOMER_LOOKUP_SCAN_LIMIT = 50

export const ADMIN_PAGE_LIMIT = 20
export const ADMIN_DENSE_PAGE_LIMIT = 30
export const LOOKUP_PRELOAD_LIMIT = 100
export const LOOKUP_SCAN_PAGE_LIMIT = 100
export const AUDIT_REPORT_LIMIT = 200
export const BATCH_ACTION_LIMIT = 20
export const LOCAL_MUTATION_PAGE_LIMIT = 8

export const ADMIN_DASHBOARD_ORDER_PAGE_LIMIT = 100
export const ADMIN_DASHBOARD_MAX_ORDER_PAGES = 20
export const MAX_LOOKUP_SCAN_PAGES = 10
