package main

import (
	"fmt"
	"log"

	"premiumhub-api/config"
	"premiumhub-api/internal/model"
)

func main() {
	cfg := config.Load()
	db := config.InitDB(cfg)

	services := []model.SosmedService{
		{
			CategoryCode:              "likes",
			Code:                      "jap-8216",
			Title:                     "Instagram Likes [No Refill] [Max: 100K] [Speed: 300K/Day]",
			ProviderCode:              "jap",
			ProviderServiceID:         "8216",
			ProviderTitle:             "Instagram Likes [No Refill] [Max: 100K] [Speed: 300K/Day]",
			PlatformLabel:             "Instagram",
			BadgeText:                 "Paling Murah",
			Theme:                     "pink",
			MinOrder:                  "10",
			StartTime:                 "5-30 Menit",
			Refill:                    "Tidak ada",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             1500,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "views",
			Code:                      "jap-5998",
			Title:                     "Instagram Photo Views [Max: 10M] [Speed: 500K/D]",
			ProviderCode:              "jap",
			ProviderServiceID:         "5998",
			ProviderTitle:             "Instagram Photo Views [Max: 10M] [Speed: 500K/D]",
			PlatformLabel:             "Instagram",
			BadgeText:                 "Paling Murah",
			Theme:                     "pink",
			MinOrder:                  "100",
			StartTime:                 "5-30 Menit",
			Refill:                    "Tidak ada",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             1000,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "likes",
			Code:                      "jap-9575",
			Title:                     "Instagram Auto Likes [HQ] [No Refill] [Max: 500K]",
			ProviderCode:              "jap",
			ProviderServiceID:         "9575",
			ProviderTitle:             "Instagram Auto Likes [HQ] [No Refill] [Max: 500K]",
			PlatformLabel:             "Instagram",
			BadgeText:                 "High Quality",
			Theme:                     "pink",
			MinOrder:                  "10",
			StartTime:                 "5-30 Menit",
			Refill:                    "Tidak ada",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             3000,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "views",
			Code:                      "jap-731",
			Title:                     "Instagram Auto Views [Max: 1M] [Speed: 1M/Day]",
			ProviderCode:              "jap",
			ProviderServiceID:         "731",
			ProviderTitle:             "Instagram Auto Views [Max: 1M] [Speed: 1M/Day]",
			PlatformLabel:             "Instagram",
			BadgeText:                 "Auto Refill",
			Theme:                     "pink",
			MinOrder:                  "100",
			StartTime:                 "5-30 Menit",
			Refill:                    "Tidak ada",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             2500,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "views",
			Code:                      "jap-669",
			Title:                     "Instagram Impressions [Photo+Explore+Home] [Max: 1M]",
			ProviderCode:              "jap",
			ProviderServiceID:         "669",
			ProviderTitle:             "Instagram Impressions [Photo+Explore+Home] [Max: 1M]",
			PlatformLabel:             "Instagram",
			BadgeText:                 "Rekomendasi",
			Theme:                     "pink",
			MinOrder:                  "10",
			StartTime:                 "5-30 Menit",
			Refill:                    "Tidak ada",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             4000,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "views",
			Code:                      "jap-6459",
			Title:                     "Instagram EMERGENCY Reel Views [Max: 5M] [Speed: 5M/D]",
			ProviderCode:              "jap",
			ProviderServiceID:         "6459",
			ProviderTitle:             "Instagram EMERGENCY Reel Views [Max: 5M] [Speed: 5M/D]",
			PlatformLabel:             "Instagram",
			BadgeText:                 "Prioritas",
			Theme:                     "pink",
			MinOrder:                  "100",
			StartTime:                 "5-30 Menit",
			Refill:                    "Tidak ada",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             3500,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "views",
			Code:                      "jap-9333",
			Title:                     "Instagram Story Views [Max: 40K] [Speed: 40K/D]",
			ProviderCode:              "jap",
			ProviderServiceID:         "9333",
			ProviderTitle:             "Instagram Story Views [Max: 40K] [Speed: 40K/D]",
			PlatformLabel:             "Instagram",
			BadgeText:                 "Rekomendasi",
			Theme:                     "pink",
			MinOrder:                  "50",
			StartTime:                 "5-30 Menit",
			Refill:                    "Tidak ada",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             4000,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "followers",
			Code:                      "jap-2989",
			Title:                     "Instagram Followers [Not Guaranteed] [Max: 25K]",
			ProviderCode:              "jap",
			ProviderServiceID:         "2989",
			ProviderTitle:             "Instagram Followers [Not Guaranteed] [Max: 25K]",
			PlatformLabel:             "Instagram",
			BadgeText:                 "Rekomendasi",
			Theme:                     "pink",
			MinOrder:                  "10",
			StartTime:                 "5-30 Menit",
			Refill:                    "30 hari",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             7500,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "followers",
			Code:                      "jap-10216",
			Title:                     "Instagram Followers [Guaranteed] [Refill: 30D] [Max: 200K]",
			ProviderCode:              "jap",
			ProviderServiceID:         "10216",
			ProviderTitle:             "Instagram Followers [Guaranteed] [Refill: 30D] [Max: 200K]",
			PlatformLabel:             "Instagram",
			BadgeText:                 "Rekomendasi",
			Theme:                     "pink",
			MinOrder:                  "10",
			StartTime:                 "5-30 Menit",
			Refill:                    "30D",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             15500,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "comments",
			Code:                      "jap-10313",
			Title:                     "Instagram Comments [Custom] [Max: 10K]",
			ProviderCode:              "jap",
			ProviderServiceID:         "10313",
			ProviderTitle:             "Instagram Comments [Custom] [Max: 10K]",
			PlatformLabel:             "Instagram",
			BadgeText:                 "Rekomendasi",
			Theme:                     "pink",
			MinOrder:                  "10",
			StartTime:                 "5-30 Menit",
			Refill:                    "Tidak ada",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             24500,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "shares",
			Code:                      "jap-6209",
			Title:                     "TikTok Saves [Refill: 30D] [Max: 2M] [Speed: 500K/D]",
			ProviderCode:              "jap",
			ProviderServiceID:         "6209",
			ProviderTitle:             "TikTok Saves [Refill: 30D] [Max: 2M] [Speed: 500K/D]",
			PlatformLabel:             "TikTok",
			BadgeText:                 "Paling Murah",
			Theme:                     "gray",
			MinOrder:                  "100",
			StartTime:                 "5-30 Menit",
			Refill:                    "30D",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             1000,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "views",
			Code:                      "jap-10161",
			Title:                     "TikTok Views [Refill: Auto 7D] [Max: 30M]",
			ProviderCode:              "jap",
			ProviderServiceID:         "10161",
			ProviderTitle:             "TikTok Views [Refill: Auto 7D] [Max: 30M]",
			PlatformLabel:             "TikTok",
			BadgeText:                 "Auto Refill",
			Theme:                     "gray",
			MinOrder:                  "100",
			StartTime:                 "5-30 Menit",
			Refill:                    "Auto 7D",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             4500,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "likes",
			Code:                      "jap-10173",
			Title:                     "TikTok Likes [HQ] [Refill: 30D] [Max: 1M]",
			ProviderCode:              "jap",
			ProviderServiceID:         "10173",
			ProviderTitle:             "TikTok Likes [HQ] [Refill: 30D] [Max: 1M]",
			PlatformLabel:             "TikTok",
			BadgeText:                 "High Quality",
			Theme:                     "gray",
			MinOrder:                  "5",
			StartTime:                 "5-30 Menit",
			Refill:                    "30D",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             4500,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "likes",
			Code:                      "jap-9998",
			Title:                     "TikTok Comment Likes [No Refill] [Max: 100K]",
			ProviderCode:              "jap",
			ProviderServiceID:         "9998",
			ProviderTitle:             "TikTok Comment Likes [No Refill] [Max: 100K]",
			PlatformLabel:             "TikTok",
			BadgeText:                 "Rekomendasi",
			Theme:                     "gray",
			MinOrder:                  "50",
			StartTime:                 "5-30 Menit",
			Refill:                    "Tidak ada",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             9000,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "followers",
			Code:                      "jap-8777",
			Title:                     "TikTok Followers [Refill: 30D] [Speed: 3K/D]",
			ProviderCode:              "jap",
			ProviderServiceID:         "8777",
			ProviderTitle:             "TikTok Followers [Refill: 30D] [Speed: 3K/D]",
			PlatformLabel:             "TikTok",
			BadgeText:                 "Rekomendasi",
			Theme:                     "gray",
			MinOrder:                  "10",
			StartTime:                 "5-30 Menit",
			Refill:                    "30D",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             47500,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "views",
			Code:                      "jap-9103",
			Title:                     "TikTok Livestream Views [Max: 100K] [Stay: 15 min]",
			ProviderCode:              "jap",
			ProviderServiceID:         "9103",
			ProviderTitle:             "TikTok Livestream Views [Max: 100K] [Stay: 15 min]",
			PlatformLabel:             "TikTok",
			BadgeText:                 "Rekomendasi",
			Theme:                     "gray",
			MinOrder:                  "50",
			StartTime:                 "5-30 Menit",
			Refill:                    "Tidak ada",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             46000,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "views",
			Code:                      "jap-5971",
			Title:                     "Youtube Views [No Refill] [Max: 10M]",
			ProviderCode:              "jap",
			ProviderServiceID:         "5971",
			ProviderTitle:             "Youtube Views [No Refill] [Max: 10M]",
			PlatformLabel:             "YouTube",
			BadgeText:                 "Rekomendasi",
			Theme:                     "yellow",
			MinOrder:                  "1.000",
			StartTime:                 "5-30 Menit",
			Refill:                    "Tidak ada",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             22500,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "likes",
			Code:                      "jap-9318",
			Title:                     "Youtube Likes [Refill: 30D] [Max: 50K]",
			ProviderCode:              "jap",
			ProviderServiceID:         "9318",
			ProviderTitle:             "Youtube Likes [Refill: 30D] [Max: 50K]",
			PlatformLabel:             "YouTube",
			BadgeText:                 "Rekomendasi",
			Theme:                     "yellow",
			MinOrder:                  "100",
			StartTime:                 "5-30 Menit",
			Refill:                    "30D",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             22500,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "comments",
			Code:                      "jap-7676",
			Title:                     "Youtube Comments [10 HQ Random] [Max: 10]",
			ProviderCode:              "jap",
			ProviderServiceID:         "7676",
			ProviderTitle:             "Youtube Comments [10 HQ Random] [Max: 10]",
			PlatformLabel:             "YouTube",
			BadgeText:                 "High Quality",
			Theme:                     "yellow",
			MinOrder:                  "1.000",
			StartTime:                 "5-30 Menit",
			Refill:                    "Tidak ada",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             61500,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "views",
			Code:                      "jap-6766",
			Title:                     "Youtube Views [RAV+Engagement] [Refill: 90D]",
			ProviderCode:              "jap",
			ProviderServiceID:         "6766",
			ProviderTitle:             "Youtube Views [RAV+Engagement] [Refill: 90D]",
			PlatformLabel:             "YouTube",
			BadgeText:                 "Rekomendasi",
			Theme:                     "yellow",
			MinOrder:                  "60.000",
			StartTime:                 "5-30 Menit",
			Refill:                    "90D",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             145500,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "followers",
			Code:                      "jap-4395",
			Title:                     "Youtube Subscribers [Max: 50K] [Speed: 2K/D]",
			ProviderCode:              "jap",
			ProviderServiceID:         "4395",
			ProviderTitle:             "Youtube Subscribers [Max: 50K] [Speed: 2K/D]",
			PlatformLabel:             "YouTube",
			BadgeText:                 "Rekomendasi",
			Theme:                     "yellow",
			MinOrder:                  "10",
			StartTime:                 "5-30 Menit",
			Refill:                    "Tidak ada",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             153000,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "views",
			Code:                      "jap-9604",
			Title:                     "Facebook Reels Views [Max: 100M] [Speed: 10M/D]",
			ProviderCode:              "jap",
			ProviderServiceID:         "9604",
			ProviderTitle:             "Facebook Reels Views [Max: 100M] [Speed: 10M/D]",
			PlatformLabel:             "Facebook",
			BadgeText:                 "Paling Murah",
			Theme:                     "blue",
			MinOrder:                  "500",
			StartTime:                 "5-30 Menit",
			Refill:                    "Tidak ada",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             2000,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "likes",
			Code:                      "jap-10098",
			Title:                     "Facebook Post Likes [No Refill] [Max: 100K]",
			ProviderCode:              "jap",
			ProviderServiceID:         "10098",
			ProviderTitle:             "Facebook Post Likes [No Refill] [Max: 100K]",
			PlatformLabel:             "Facebook",
			BadgeText:                 "Rekomendasi",
			Theme:                     "blue",
			MinOrder:                  "10",
			StartTime:                 "5-30 Menit",
			Refill:                    "Tidak ada",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             9500,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "followers",
			Code:                      "jap-9274",
			Title:                     "Facebook Profile Followers [HQ] [Max: 50K]",
			ProviderCode:              "jap",
			ProviderServiceID:         "9274",
			ProviderTitle:             "Facebook Profile Followers [HQ] [Max: 50K]",
			PlatformLabel:             "Facebook",
			BadgeText:                 "High Quality",
			Theme:                     "blue",
			MinOrder:                  "100",
			StartTime:                 "5-30 Menit",
			Refill:                    "Tidak ada",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             10500,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "likes",
			Code:                      "jap-1889",
			Title:                     "Facebook Page Likes + Followers [Refill: 15D] [Max: 1M]",
			ProviderCode:              "jap",
			ProviderServiceID:         "1889",
			ProviderTitle:             "Facebook Page Likes + Followers [Refill: 15D] [Max: 1M]",
			PlatformLabel:             "Facebook",
			BadgeText:                 "Rekomendasi",
			Theme:                     "blue",
			MinOrder:                  "50",
			StartTime:                 "5-30 Menit",
			Refill:                    "15D",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             17000,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "views",
			Code:                      "jap-7381",
			Title:                     "Telegram Views [1 post] [Fast] [Non Drop] [Max: 100K]",
			ProviderCode:              "jap",
			ProviderServiceID:         "7381",
			ProviderTitle:             "Telegram Views [1 post] [Fast] [Non Drop] [Max: 100K]",
			PlatformLabel:             "Telegram",
			BadgeText:                 "Paling Murah",
			Theme:                     "blue",
			MinOrder:                  "10",
			StartTime:                 "Instan",
			Refill:                    "Tidak ada",
			ETA:                       "1 Jam",
			CheckoutPrice:             1000,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "views",
			Code:                      "jap-8611",
			Title:                     "Telegram Auto Views [1 post] [Non Drop] [Max: 100K]",
			ProviderCode:              "jap",
			ProviderServiceID:         "8611",
			ProviderTitle:             "Telegram Auto Views [1 post] [Non Drop] [Max: 100K]",
			PlatformLabel:             "Telegram",
			BadgeText:                 "Auto Refill",
			Theme:                     "blue",
			MinOrder:                  "10",
			StartTime:                 "5-30 Menit",
			Refill:                    "Tidak ada",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             1000,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "likes",
			Code:                      "jap-8612",
			Title:                     "Telegram Positive Reactions [Max: 4M]",
			ProviderCode:              "jap",
			ProviderServiceID:         "8612",
			ProviderTitle:             "Telegram Positive Reactions [Max: 4M]",
			PlatformLabel:             "Telegram",
			BadgeText:                 "Rekomendasi",
			Theme:                     "blue",
			MinOrder:                  "50",
			StartTime:                 "5-30 Menit",
			Refill:                    "Tidak ada",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             2500,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "followers",
			Code:                      "jap-7102",
			Title:                     "Telegram Members [Refill: 3D] [Max: 30K]",
			ProviderCode:              "jap",
			ProviderServiceID:         "7102",
			ProviderTitle:             "Telegram Members [Refill: 3D] [Max: 30K]",
			PlatformLabel:             "Telegram",
			BadgeText:                 "Rekomendasi",
			Theme:                     "blue",
			MinOrder:                  "10",
			StartTime:                 "5-30 Menit",
			Refill:                    "3D",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             3500,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "views",
			Code:                      "jap-2098",
			Title:                     "Twitter Tweet Views [Non Drop] [Max: 100M]",
			ProviderCode:              "jap",
			ProviderServiceID:         "2098",
			ProviderTitle:             "Twitter Tweet Views [Non Drop] [Max: 100M]",
			PlatformLabel:             "Twitter",
			BadgeText:                 "Paling Murah",
			Theme:                     "blue",
			MinOrder:                  "100",
			StartTime:                 "5-30 Menit",
			Refill:                    "Tidak ada",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             1000,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "likes",
			Code:                      "jap-9393",
			Title:                     "Twitter Likes [No Refill] [Max: 10K]",
			ProviderCode:              "jap",
			ProviderServiceID:         "9393",
			ProviderTitle:             "Twitter Likes [No Refill] [Max: 10K]",
			PlatformLabel:             "Twitter",
			BadgeText:                 "Rekomendasi",
			Theme:                     "blue",
			MinOrder:                  "50",
			StartTime:                 "5-30 Menit",
			Refill:                    "Tidak ada",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             6000,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "shares",
			Code:                      "jap-8860",
			Title:                     "Twitter Retweets [No Refill] [Max: 15K]",
			ProviderCode:              "jap",
			ProviderServiceID:         "8860",
			ProviderTitle:             "Twitter Retweets [No Refill] [Max: 15K]",
			PlatformLabel:             "Twitter",
			BadgeText:                 "Rekomendasi",
			Theme:                     "blue",
			MinOrder:                  "10",
			StartTime:                 "5-30 Menit",
			Refill:                    "Tidak ada",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             6500,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "followers",
			Code:                      "jap-9011",
			Title:                     "Twitter Followers [Refill: 7D] [Max: 2.5K]",
			ProviderCode:              "jap",
			ProviderServiceID:         "9011",
			ProviderTitle:             "Twitter Followers [Refill: 7D] [Max: 2.5K]",
			PlatformLabel:             "Twitter",
			BadgeText:                 "Rekomendasi",
			Theme:                     "blue",
			MinOrder:                  "10",
			StartTime:                 "5-30 Menit",
			Refill:                    "7D",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             18500,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "views",
			Code:                      "jap-9214",
			Title:                     "Shopee Live Views [15 Minutes] [Max: 10K]",
			ProviderCode:              "jap",
			ProviderServiceID:         "9214",
			ProviderTitle:             "Shopee Live Views [15 Minutes] [Max: 10K]",
			PlatformLabel:             "Shopee",
			BadgeText:                 "Rekomendasi",
			Theme:                     "orange",
			MinOrder:                  "50",
			StartTime:                 "5-30 Menit",
			Refill:                    "Tidak ada",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             95000,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "views",
			Code:                      "jap-1486",
			Title:                     "Indonesia Traffic from Google [No Refill] [Max: 1M]",
			ProviderCode:              "jap",
			ProviderServiceID:         "1486",
			ProviderTitle:             "Indonesia Traffic from Google [No Refill] [Max: 1M]",
			PlatformLabel:             "Website Traffic",
			BadgeText:                 "Rekomendasi",
			Theme:                     "blue",
			MinOrder:                  "100",
			StartTime:                 "5-30 Menit",
			Refill:                    "Tidak ada",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             12500,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "views",
			Code:                      "jap-902",
			Title:                     "Spotify USA Free Plays [Lifetime Guaranteed] [Max: 50K]",
			ProviderCode:              "jap",
			ProviderServiceID:         "902",
			ProviderTitle:             "Spotify USA Free Plays [Lifetime Guaranteed] [Max: 50K]",
			PlatformLabel:             "Spotify",
			BadgeText:                 "Rekomendasi",
			Theme:                     "blue",
			MinOrder:                  "500",
			StartTime:                 "5-30 Menit",
			Refill:                    "Tidak ada",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             6500,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "views",
			Code:                      "jap-2121",
			Title:                     "Spotify Global Free Plays [Refill: 365D] [Max: 500K]",
			ProviderCode:              "jap",
			ProviderServiceID:         "2121",
			ProviderTitle:             "Spotify Global Free Plays [Refill: 365D] [Max: 500K]",
			PlatformLabel:             "Spotify",
			BadgeText:                 "Rekomendasi",
			Theme:                     "blue",
			MinOrder:                  "500",
			StartTime:                 "5-30 Menit",
			Refill:                    "365D",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             6500,
			SortOrder:                 100,
			IsActive:                  true,
		},
		{
			CategoryCode:              "shares",
			Code:                      "jap-1937",
			Title:                     "Spotify Saves for Track [Lifetime Guaranteed] [Max: 1M]",
			ProviderCode:              "jap",
			ProviderServiceID:         "1937",
			ProviderTitle:             "Spotify Saves for Track [Lifetime Guaranteed] [Max: 1M]",
			PlatformLabel:             "Spotify",
			BadgeText:                 "Rekomendasi",
			Theme:                     "blue",
			MinOrder:                  "100",
			StartTime:                 "5-30 Menit",
			Refill:                    "Tidak ada",
			ETA:                       "1-6 Jam",
			CheckoutPrice:             13500,
			SortOrder:                 100,
			IsActive:                  true,
		},
	}

	count := 0
	for _, s := range services {
		var existing model.SosmedService
		if err := db.Where("code = ?", s.Code).First(&existing).Error; err != nil {
			if err := db.Create(&s).Error; err != nil {
				log.Printf("Failed to insert %s: %v", s.Code, err)
			} else {
				count++
			}
		} else {
			existing.CheckoutPrice = s.CheckoutPrice
			existing.Title = s.Title
			db.Save(&existing)
		}
	}

	fmt.Printf("✓ Berhasil seed %d layanan JAP ke database!
", count)
}
